import type { Metadata } from "next";
import "./globals.css";
import { ThemeProvider } from "@repo/shadcn/providers/theme-provider";
import Navbar from "@/layout/Navbar";
import Footer from "@/layout/Footer";
import { AuthProvider } from "@/auth";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          // disableTransitionOnChange
        >
          <AuthProvider>
            <div className="w-full min-h-screen">
              <Navbar />
              <main className="flex-1">{children}</main>
              <Footer />
            </div>
          </AuthProvider>
        </ThemeProvider>
      </body>
    </html>
  );
}
